development:
  dialect: "mysql"
  database: "oscars_development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

test:
  dialect: "mysql"
  database: "oscars_test"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/oscars_production"}}