version: "2"

services:

    oscars_website:
        image: golang
        working_dir: /go/src/app
        command: go run oscars.go
        volumes:
            - ./website/:/go/src/app
        networks:
            main:
                aliases:
                    - oscars_website

    oscars_kong:
        image: kong
        restart: always
        ports:
            - 8000:8000
            - 8001
        environment:
            - KONG_DATABASE=cassandra
            - KONG_CASSANDRA_CONTACT_POINTS=oscars_kong_cassandra
            - KONG_LOG_LEVEL=debug
        networks:
            main:
                aliases:
                    - oscars_kong

    oscars_kong_cassandra:
        image:  cassandra:2.2
        restart: always
        expose:
            - 9042
        volumes:
            - ./data/kong/cassandra:/var/lib/cassandra
        networks:
            main:
                aliases:
                    - oscars_kong_cassandra

    oscars_kong_dashboard:
        image: robertgwillard/kong-dashboard:v1.1.2
        restart: always
        ports:
            - 8002:8080

    oscars_nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - .default.conf:/etc/nginx/conf.d/default.conf
        networks:
            main:
                aliases:
                    - oscars_nginx

networks:
    main:
